### PR TITLE
Support sealed family (trait) and object

### PR DESCRIPTION
**Pull request by cchantep**
See use case: https://gist.github.com/cchantep/df343806fc826aabdede4833cd06c619

### CODE REVIEW

**Comment by miloszpp** [comment]
@karolchmist unfortunately I don't have time to maintain this project any more.

**Comment by cchantep** [comment]
Hi, let see what can be done for this repo (either fork or transfer). best regards.

**Comment by miloszpp** [comment]
@cchantep I'd be happy to add you as co-owner of this repo.

**Comment by cchantep** [comment]
With settings access? If yes go with that.

**Comment by cchantep** [comment]
Done on my side

**Pull request merged**
